### PR TITLE
J4

### PR DESCRIPTION
**Pull request by aydun**
Various changes for Joomla 4.

Also allows unlimited Membership Status and Type rules, but the config is not backwards compatible.  See  README.md

Replaces direct SQL with Civi API.

This has been tested on a couple of J4 sites.  It has not been tested on J3 - the thought being to create separate J3 & J4 releases.

### CODE REVIEW

**Comment by aydun** [comment]
ping @vingle

**Comment by vingle** [comment]
Thanks @aydun – this version upgrades and seems to be working well.

**Comment by vingle** [comment]
@lcdservices – this PR is good to merge.

**Comment by monishdeb** [comment]
I can confirm the patch works on my J4 setup. Ready for merge.

**Pull request merged**
